# C??????????keyword ? knowledgePoint?
# ??????????????????
??=??
malloc=??
free=??
calloc=??
??=??
??=??

??=??
??=??
??=??
??=??
??=??

???=????????
strlen=????????
strcpy=????????
strcmp=????????

??=????
for=????
while=????
break=????
continue=????
??=????

??=??
??=??
???=??
??=??

??=???????
int=???????
float=???????
char=???????
double=???????
??=???????
??=???????

scanf=????
printf=????
??=????
??=????

if=????
switch=????
else=????
??=????

???=???
struct=???
typedef=???

??=????
fopen=????
fclose=????
fprintf=????
fscanf=????